# Generated by Django 4.2.28 on 2026-02-06 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_table_item_qr_code'),
        ('qrcodes', '0001_initial'),
        ('orders', '0002_orderitem_orderitemmodifier_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='qrcodes.qrcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, help_text='Cart session ID for linking with customer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.table'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['qr_code'], name='orders_orde_qr_code_880982_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['session_id'], name='orders_orde_session_aeca3b_idx'),
        ),
        migrations.AddField(
            model_name='orderitemmodifier',
            name='modifier_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.modifieroption'),
        ),
        migrations.AddField(
            model_name='orderitemmodifier',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitemmodifier',
            unique_together={('order_item', 'modifier_option')},
        ),
    ]
