# Generated by Django 4.2.28 on 2026-02-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_status',
            old_name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_created_at',
            old_name='orders_orde_created_0e92de_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_status_created_at',
            old_name='orders_orde_status_25e057_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_qr_code',
            old_name='orders_orde_qr_code_880982_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='idx_order_session_id',
            old_name='orders_orde_session_aeca3b_idx',
        ),
    ]
